spring:
  datasource :
      url : jdbc:h2:tcp://localhost/~/test
      username : sa
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create #create : 테이블이 있으면 드랍하고 새로 생성하는 옵션
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      #show_sql: true #얘도 하이버네이트의 sql을 볼 수 있는데 얘는 system.out.println으로 찍혀나옴
    open-in-view: true
    #하이버네이트가 생성하는 sql을 볼 수 있음. 얘는 log로 나옴
  logging:
    level:
      org.hibernate.SQL: debug
      #org.hibernate.type: true #이 설정을 해주면 ?, ?로 나오는 쿼리 파라미터를 1번에는 뭐, 2번에는 뭐라고 자세하게 로그로 찍어줌.